### ISSUE TITLE
Notifier: The test for mailto should be case insensitive. 

### ISSUE THREAD

**Issue by douglm** [Bedework/bedework#101]
I've seen upper case mailto: 

Scheme names consist of a sequence of characters beginning with a letter and followed by any combination of letters, digits, plus ("+"), period ("."), or hyphen ("-"). Although schemes are case- insensitive, the canonical form is lowercase and documents that specify schemes must do so with lowercase letters. An implementation should accept uppercase letters as equivalent to lowercase in scheme names (e.g., allow "HTTP" as well as "http") for the sake of robustness but should only produce lowercase scheme names for consistency.

**Comment by ggallen** [comment]
Closed with pull request #4.
