### ISSUE TITLE
From Jira: Bookmarkable URLs

### ISSUE THREAD

**Issue by bleibson** [Bedework/bedework#62]
See https://issues.jasig.org/browse/BWK-38

**Comment by kyletcook** [comment]
Our users would like to be able to copy/paste URL from the address bar of their browser for individual events (event detail). This is not available with current xsl view writing to the URL of the browser's address bar.

**Comment by kyletcook** [comment]
@douglm Testing our instance at https://eventsdev.library.nashville.org; I am seeing this working in Mozilla Firefox. 

In current 3.10 bedework, event detail shows `https://events.library.nashville.org/cal/event/showEventMore.rdo` for all individual event displays.
In Bedework 4: Address bar is presenting a unique url to each event on the "events Detail view". appedning this `?b=de&href=/public/unbrowsable/workflow/unapproved/CAL-8a3e8e4b-83f1` after the `eventView.do`; 

Has their been a code change that will be presenting users with a permanent URL for the event detail in their address bar?

**Comment by kyletcook** [comment]
Happy to report this is all fixed in Bedework 4. Can retire this issue! @bleibson
