### ISSUE TITLE
Only superusers can upload images.  Should work for any cal admin

### ISSUE THREAD

**Issue by bleibson** [Bedework/bedework#91]

**Comment by bleibson** [comment]
Worked around with a stylesheet change, but should be fixed correctly.  Work around is in the test (line 260 of calendar.xsl ...in <xsl:template match="calendar" mode="selectCalForEventCalTree">) to look for the superuser:

(currentAccess/current-user-privilege-set/privilege/write-content or /bedework/userInfo/superUser = 'true') and (calType != '0')

**Comment by spartanicus** [comment]
The workaround is to 
a) ensure that there is a valid image directory (e.g. /public/images )
b) comment out the xsl:if test at line 2467 of eventsForm.xsl in the admin theme:
 ....  

The imageUploadDirectory is not getting returned to normal admins in the xml (and it should be).

**Comment by spartanicus** [comment]
Fixed as of 3.10.2
