### ISSUE TITLE
broken spanish translation for caladmin

### ISSUE THREAD

**Issue by pasqualm** [Bedework/bedework#96]
Hi
I have my browser configured to use spanish as my default language, the pages in the public calendar are correctly shown in spanish but when I access any of the calendar administration pages (http://localhost:8080/caladmin) the browser only shows a blank page after the authentication. 

If I change the default language back to english all the pages are correctly shown. I have started jboss in debug mode and the problem seems to be related to xlst transformations

Versions 3.9 and 3.10 are affected

**Comment by pasqualm** [comment]
The related server.log file can be found here:
https://mega.nz/#!Y1xTQKiD!WjYdd9cYbogDIh3OnRyV5STGCL556bMaC8NLO6DK7hE

**Comment by njodessit** [comment]
Looks like some variables that are defined in "quickstart-3.10\bedework\deployment\webadmin\webapp\resources\default\default\globals.xsl" were not copied over to "quickstart-3.10\bedework\deployment\webadmin\webapp\resources\es_ES\default\globals.xsl"

But this should have affected v 3.10 only - there's no tabs.xsl file in v.3.9
![globals_diff](https://cloud.githubusercontent.com/assets/2333873/8571152/ebf0c554-2552-11e5-9ace-b5d549c601f8.JPG)

**Comment by spartanicus** [comment]
@njodessit - that's correct: this should only impact version 3.10.
Bedework is largely backwards compatible with older themes - you can generally run older themes in a newer version, but you generally can't run a newer theme in an older version unless you make certain that the strings.xsl files are up to date too. 

I've just committed a fix for this in 3.10.

**Comment by spartanicus** [comment]
Fixed as of SVN commit #4527

**Comment by pasqualm** [comment]
Thanks for the fast resolution

If you can take also a look to the german translation, if you use it the caladmin pages are displayed in english instead of german so there must be another issue with that

Thank you :)

**Comment by spartanicus** [comment]
No issue there - we have no German translation for the admin client so the system falls back to the default language folder (literally "default" - which is essentially en_US).  We'd love to have a German translation!  :)

**Comment by spartanicus** [comment]
Hi, Pasqual -

Thanks for the heads up!  We've fixed the issue for 3.10
https://github.com/Bedework/bedework/issues/96

An SVN checkout of the admin client resources will get the changes, and 
you can just copy the contents of 
bedework/deployment/webadmin/webapp/resources from the source into place 
in jboss jboss-5.1.0.GA/server/default/deploy/ROOT.war/caladminrsrc/  
(don't overwrite any theme work you've done down in jboss, of course, if 
for any reason it's not copied elsewhere).

Note that there are still a few blocks of strings that remain 
untranslated in the new es_ES/strings.xsl file - but perhaps we can get 
that tended to.

I'll take a look at 3.9 as well - I suspect something may have been 
merged and not translated.

Best wishes -
Arlen
